import '~/css/global.scss'

import { Playfair_Display } from 'next/font/google'

const font = Playfair_Display({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'create-bsmnt-app',
  description: 'Generated by create-bsmnt-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
